
exclude: '^(\.|_|output/?|livedata/?|tmp/?|logs/?|interactive/?).*$'

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict

-   repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        exclude: '^(\.|_|output/?|livedata/?|tmp/?|logs/?|processing/?).*$'

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        additional_dependencies:
        -   'pydantic~=1.9.0'
        -   'types-requests'
        -   'types-PyYAML'
        -   'types-setuptools'

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
        args: ['--diff']

-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
    -   id: isort
        name: isort (python)
        args: ['--check-only']
